import random

existing_genes = {
    "TP53", "BRCA1", "INS", "CFTR", "APOE", "ACTB", "HBB", "MAOA", "HTT", "EGFR",
    "MTHFR", "LDLR", "ALB", "F8", "DMD", "PAH", "G6PD", "COL1A1", "IL6", "POMC",
    "ACE", "HER2", "SOD1", "GBA", "SHH", "SIRT1", "GAPDH", "MYH7", "RYR1", "FBN1",
    "PCSK9", "FOXP2", "LCT", "MC1R", "CCR5", "UCP1", "PRNP", "CREB1", "CLOCK",
    "OPN1LW", "DRD4", "VEGFA", "ESR1", "KIT", "VHL", "CTCF", "TNF", "MTOR", "PTEN",
    "PARP1", "NOS3", "BDNF", "LEP", "GHRH", "CASP3", "TERT", "CRY1", "PER2", "AVP",
    "OXT", "GRIN2B", "SLC6A4", "COMT", "GAD1", "CHRNA7", "SCN5A", "KCNH2", "PLN",
    "TNNT2", "MYBPC3", "ABCA1", "APOA1", "CETP", "HMGCR", "SLC2A4", "PPARG", "IRS1",
    "ADIPOQ", "GH1", "IGF1", "TSHR", "TPO", "PTH", "VDR", "ALPL", "RUNX2", "SP7",
    "SOX9", "COL2A1", "FLG", "TYR", "KRT1", "ELN", "CD4", "IL2", "FOXP3", "AICDA", "MHC"
}

# Add more real genes to reach 900
additional_real_genes = [
    # Metabolism
    ("GYS2", "Glycogen Synthase 2", "Liver isoform of glycogen synthase."),
    ("PYGM", "Glycogen Phosphorylase, Muscle Type", "Breaks down glycogen in skeletal muscle."),
    ("ENO1", "Alpha-Enolase", "Glycolytic enzyme that converts 2-phosphoglycerate to phosphoenolpyruvate."),
    ("ENO2", "Gamma-Enolase", "Found primarily in neurons and neuroendocrine cells."),
    ("ENO3", "Beta-Enolase", "Specific to muscle tissue."),
    ("PGK1", "Phosphoglycerate Kinase 1", "Major enzyme in the ATP-generating step of glycolysis."),
    ("PGAM1", "Phosphoglycerate Mutase 1", "Catalyzes the internal transfer of a phosphate group in glycolysis."),
    ("TPI1", "Triosephosphate Isomerase 1", "Interconverts dihydroxyacetone phosphate and D-glyceraldehyde 3-phosphate."),
    ("ALDOA", "Aldolase A", "Involved in glycolysis and gluconeogenesis in muscle."),
    ("ALDOB", "Aldolase B", "Enzyme for fructose metabolism in the liver."),
    ("ALDOC", "Aldolase C", "Found in the brain and nervous system."),
    ("GAPDHS", "Glyceraldehyde-3-Phosphate Dehydrogenase, Spermatogenic", "Sperm-specific glycolytic enzyme."),
    ("ACO2", "Aconitase 2", "Mitochondrial enzyme that catalyzes the second step of the TCA cycle."),
    ("DLD", "Dihydrolipoamide Dehydrogenase", "Subunit of several multi-enzyme complexes in metabolism."),
    ("DLAT", "Dihydrolipoamide S-Acetyltransferase", "Subunit of the pyruvate dehydrogenase complex."),
    ("SUCLA2", "Succinate-CoA Ligase GDP-Forming Beta Subunit", "Involved in the synthesis of ATP in the TCA cycle."),
    ("SUCLG1", "Succinate-CoA Ligase Alpha Subunit", "Catalyzes the reversible conversion of succinyl-CoA to succinate."),
    ("SDHC", "Succinate Dehydrogenase Complex Subunit C", "Membrane-anchored subunit of Complex II."),
    ("SDHD", "Succinate Dehydrogenase Complex Subunit D", "Membrane-anchored subunit involved in electron transport."),
    ("MDH2", "Malate Dehydrogenase 2, Mitochondrial", "Catalyzes the oxidation of malate to oxaloacetate in the TCA cycle."),
    ("NDUFA1", "NADH:Ubiquinone Oxidoreductase Subunit A1", "Accessory subunit of mitochondrial Complex I."),
    ("NDUFB1", "NADH:Ubiquinone Oxidoreductase Subunit B1", "Component of the mitochondrial respiratory chain Complex I."),
    ("UQCRC1", "Ubiquinol-Cytochrome C Reductase Core Protein 1", "Part of the mitochondrial respiratory chain Complex III."),
    ("UQCRB", "Ubiquinol-Cytochrome C Reductase Binding Protein", "Component of the Complex III assembly."),
    ("COX5A", "Cytochrome C Oxidase Subunit 5A", "Nuclear-encoded subunit of mitochondrial Complex IV."),
    ("COX6A1", "Cytochrome C Oxidase Subunit 6A1", "Regulatory subunit of Cytochrome C Oxidase."),
    ("ATP5F1B", "ATP Synthase F1 Subunit Beta", "Catalytic subunit of mitochondrial ATP synthase."),
    ("ATP5F1C", "ATP Synthase F1 Subunit Gamma", "Central stalk of the mitochondrial ATP synthase."),
    # Signaling
    ("PRKACB", "Protein Kinase cAMP-Activated Catalytic Subunit Beta", "Mediates cAMP signaling in many tissues."),
    ("PRKAR1A", "Protein Kinase cAMP-Dependent Type I Regulatory Subunit Alpha", "Regulates the activity of Protein Kinase A."),
    ("PRKAR2A", "Protein Kinase cAMP-Dependent Type II Regulatory Subunit Alpha", "Involved in PKA signaling localization."),
    ("CALM1", "Calmodulin 1", "Universal calcium sensor that regulates many proteins."),
    ("CALM2", "Calmodulin 2", "Highly conserved calcium-binding protein."),
    ("CALM3", "Calmodulin 3", "Essential for calcium-dependent signaling."),
    ("CAMK1", "Calcium/Calmodulin Dependent Protein Kinase I", "Involved in cell cycle and calcium signaling."),
    ("CAMK4", "Calcium/Calmodulin Dependent Protein Kinase IV", "Regulates transcription in the brain and immune system."),
    ("PRKCB", "Protein Kinase C Beta", "Involved in B cell signaling and diabetic complications."),
    ("PRKCD", "Protein Kinase C Delta", "Plays a role in apoptosis and cell growth regulation."),
    ("PRKCE", "Protein Kinase C Epsilon", "Involved in pain signaling and cardiac protection."),
    ("PRKCQ", "Protein Kinase C Theta", "Essential for T cell activation."),
    ("PRKCZ", "Protein Kinase C Zeta", "Involved in cell polarity and NF-kappaB signaling."),
    ("MAP3K1", "Mitogen-Activated Protein Kinase Kinase Kinase 1", "Regulates the JNK and ERK signaling pathways."),
    ("MAP3K5", "Mitogen-Activated Protein Kinase Kinase Kinase 5 (ASK1)", "Activated by stress to induce apoptosis."),
    ("MAP3K7", "Mitogen-Activated Protein Kinase Kinase Kinase 7 (TAK1)", "Key mediator of cytokine signaling."),
    ("MAP2K4", "Mitogen-Activated Protein Kinase Kinase 4", "Activates the JNK signaling pathway."),
    ("MAP2K7", "Mitogen-Activated Protein Kinase Kinase 7", "Primary activator of the JNK pathway."),
    ("MAPK8", "Mitogen-Activated Protein Kinase 8 (JNK1)", "Involved in stress response and apoptosis."),
    ("MAPK9", "Mitogen-Activated Protein Kinase 9 (JNK2)", "Regulates cell proliferation and differentiation."),
    ("MAPK10", "Mitogen-Activated Protein Kinase 10 (JNK3)", "Brain-specific stress-activated kinase."),
    ("MAPK14", "Mitogen-Activated Protein Kinase 14 (p38 alpha)", "Major responder to stress and inflammation."),
    ("MAPK11", "Mitogen-Activated Protein Kinase 11 (p38 beta)", "Involved in inflammatory signaling."),
    ("MAPK12", "Mitogen-Activated Protein Kinase 12 (p38 gamma)", "Regulates muscle differentiation."),
    ("MAPK13", "Mitogen-Activated Protein Kinase 13 (p38 delta)", "Involved in skin and lung signaling."),
    ("PDPK1", "3-Phosphoinositide Dependent Protein Kinase 1", "Master kinase that activates AKT and S6K."),
    ("MTOR", "Mammalian Target of Rapamycin", "Master regulator of cell growth."),
    ("RICTOR", "RPTOR Independent Companion of MTOR Complex 2", "Essential component of MTORC2."),
    ("RPTOR", "Regulatory Associated Protein of MTOR Complex 1", "Essential component of MTORC1."),
    ("TSC1", "Tuberous Sclerosis 1", "Inhibits MTOR signaling."),
    ("TSC2", "Tuberous Sclerosis 2", "Negative regulator of cell growth via MTOR."),
    ("RHEB", "Ras Homolog Enriched in Brain", "Activator of the MTORC1 complex."),
    # Structural
    ("COL6A1", "Collagen Type VI Alpha 1 Chain", "Forms microfibrils in the extracellular matrix."),
    ("COL6A2", "Collagen Type VI Alpha 2 Chain", "Structural component of connective tissues."),
    ("COL6A3", "Collagen Type VI Alpha 3 Chain", "Essential for anchoring basement membranes."),
    ("COL7A1", "Collagen Type VII Alpha 1 Chain", "Main component of anchoring fibrils in the skin."),
    ("COL9A1", "Collagen Type IX Alpha 1 Chain", "Found in cartilage and helps organize the matrix."),
    ("COL11A1", "Collagen Type XI Alpha 1 Chain", "Regulates the diameter of collagen fibrils in cartilage."),
    ("COL12A1", "Collagen Type XII Alpha 1 Chain", "Involved in organizing collagen fibers in tendons."),
    ("COL17A1", "Collagen Type XVII Alpha 1 Chain", "Transmembrane protein in hemidesmosomes."),
    ("COL18A1", "Collagen Type XVIII Alpha 1 Chain", "Precursor of endostatin, an inhibitor of angiogenesis."),
    ("ACTN1", "Alpha-Actinin 1", "Crosslinks actin filaments in non-muscle cells."),
    ("ACTN2", "Alpha-Actinin 2", "Major component of the Z-disc in cardiac and skeletal muscle."),
    ("ACTN3", "Alpha-Actinin 3", "Found in fast-twitch muscle fibers; the 'sprint gene'."),
    ("ACTN4", "Alpha-Actinin 4", "Involved in cell motility and kidney function."),
    ("MYO1A", "Myosin IA", "Involved in the movement of microvilli in the gut."),
    ("MYO1C", "Myosin IC", "Involved in hearing and glucose transport."),
    ("MYO1E", "Myosin IE", "Essential for kidney filtration function."),
    ("MYO2A", "Myosin IIA", "Non-muscle myosin involved in cell contraction and shape."),
    ("MYO6", "Myosin VI", "Motor protein that moves toward the minus end of actin filaments."),
    ("MYO10", "Myosin X", "Required for the formation of filopodia."),
    ("FLNA", "Filamin A", "Crosslinks actin filaments and links them to membrane proteins."),
    ("FLNB", "Filamin B", "Essential for skeletal development."),
    ("FLNC", "Filamin C", "Structural protein in cardiac and skeletal muscle."),
    ("KRT2", "Keratin 2", "Expressed in the upper layers of the epidermis."),
    ("KRT3", "Keratin 3", "Specific to the corneal epithelium of the eye."),
    ("KRT4", "Keratin 4", "Found in non-keratinized stratified squamous epithelia."),
    ("KRT6A", "Keratin 6A", "Induced by wounding and stress in the skin."),
    ("KRT7", "Keratin 7", "Found in simple ductal epithelia."),
    ("KRT9", "Keratin 9", "Specific to the skin of the palms and soles."),
    ("KRT12", "Keratin 12", "Maintains the structural integrity of the cornea."),
    ("KRT13", "Keratin 13", "Expressed in internal mucosal linings."),
    ("KRT15", "Keratin 15", "Marker for hair follicle stem cells."),
    ("KRT16", "Keratin 16", "Expressed during rapid skin cell proliferation."),
    ("KRT17", "Keratin 17", "Involved in nail and hair development."),
    ("KRT19", "Keratin 19", "Smallest keratin; used as a marker for cancer cells."),
    ("KRT20", "Keratin 20", "Specific to the intestinal epithelium and Merkel cells."),
    ("LMNB2", "Lamin B2", "Nuclear envelope protein involved in brain development."),
    ("SUN1", "SUN Domain Containing 1", "Links the nucleus to the cytoskeleton."),
    ("SUN2", "SUN Domain Containing 2", "Involved in nuclear positioning and migration."),
    ("SYNE3", "Nesprin 3", "Links the nuclear envelope to intermediate filaments."),
    ("SYNE4", "Nesprin 4", "Essential for the positioning of the nucleus in outer hair cells."),
    ("BICD2", "Bicaudal D Cargo Adaptor 2", "Involved in the transport of organelles along microtubules."),
    ("KIF1B", "Kinesin Family Member 1B", "Transports mitochondria and synaptic vesicle precursors."),
    ("KIF21A", "Kinesin Family Member 21A", "Motor protein involved in eye movement control."),
    ("KIF11", "Kinesin Family Member 11", "Essential for the formation of the mitotic spindle."),
    ("KIF2A", "Kinesin Family Member 2A", "Regulates microtubule length in neurons."),
    ("KIFC1", "Kinesin Family Member C1", "Involved in spindle assembly in cancer cells."),
    ("DYNLL1", "Dynein Light Chain LC8-Type 1", "Highly conserved subunit of the dynein motor."),
    ("DYNC1I1", "Dynein Cytoplasmic 1 Intermediate Chain 1", "Involved in dynein-mediated transport in neurons."),
    ("DCTN1", "Dynactin Subunit 1", "Largest subunit of the dynactin complex."),
    ("DCTN2", "Dynactin Subunit 2", "Component of the dynactin complex for dynein activation."),
]

# I'll just combine everything now.
# I'll reuse the categories from the previous script and add these.

